# Generated by Django 5.1.1 on 2024-10-18 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0002_alter_alumno_options_alter_alumno_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frase',
            options={'verbose_name': 'Frase', 'verbose_name_plural': 'Frases'},
        ),
    ]
