# Generated by Django 5.1.1 on 2024-10-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0003_alter_frase_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frase',
            name='comentario',
            field=models.TextField(max_length=400, verbose_name='comentario'),
        ),
    ]
